@startuml
!pragma teoz true

box "Raspberry Pico PCB" #LightGreen
  participant "MiOTY Transmitter" as MiotyT
end box

box "MiotyReciever" #LightYellow
  participant "Mioty Antenna" as MiotyA
  participant "MQTT Broker" as MQTT
end box

box "University Server" #Salmon
  participant "MqttToDBInterface" as MTDB
  database "InfluxDB" as InfluxDB
  participant "Grafana" as Grafana
end box

actor User as User

group setup
  MTDB->MQTT: subscribe
end

group onMessage
  MiotyT -> MiotyA: send message
  MiotyA -> MQTT: publish message
  MQTT -> MTDB: distribute message
  MTDB -> MTDB: decode message
  MTDB -> InfluxDB: store data
end

group useDashboard
  User -> Grafana: request data
  Grafana -> InfluxDB: query data
  InfluxDB -> InfluxDB: evaluate query and collect results
  InfluxDB -> Grafana: send results
  Grafana -> User: display results
end

@enduml